### ISSUE TITLE
[REQUESTS]Xanmod Latest Mainline 5.15 is out.

### ISSUE THREAD

**Issue by wastee** [bigshans/linux-xanmod-cacule-anbox-cjktty#2]
![5.15 is out](https://user-images.githubusercontent.com/22229962/140631770-5b4334e7-bfd3-4bda-99c7-77e2ace115b0.png)
Hope merge soon. Thank's your work.

**Comment by bigshans** [comment]
I know this. But I don't know why xanmod-cacule is still not merged officially. If you don't need cacule, you can try linux-xanmod. Thank you for your support.

**Comment by bigshans** [comment]
I updated xanmod-tt. The response from the current experience is very good, you can try to experience it. The code is in the tt branch, and the packaged package has been uploaded. Other content has not changed.

**Comment by bigshans** [comment]
But TT is still not perfect, please consider carefully when putting it into production.

**Comment by wastee** [comment]
I use xanmod-tt 10+ hours. Its response feels faster than cacule. 
I use cacule for audio work, so i compare them in audio latency. In audio work, TT latency is the same as cacule.
I can't find more info about TT. Where can i get more info about it?

**Comment by bigshans** [comment]
You can see more info from https://github.com/hamadmarri/TT-CPU-Scheduler . TT was written by the author of Cacule, and he has archived cacule. TT is still a testing version, but I suggest paying attention to TT.

**Comment by wastee** [comment]
> But TT is still not perfect, please consider carefully when putting it into production.

You are right about it. Xanmod-tt DO have some issues in my workflow either v5.15.1 and v5.15.2. 
It's an amazing scheduler. I look forward to its stable version.
