### ISSUE TITLE
Wrong repo name

### ISSUE THREAD

**Issue by wastee** [bigshans/linux-xanmod-cacule-anbox-cjktty#3]
"caucle" should be "cacule".

![cacule](https://user-images.githubusercontent.com/22229962/140631802-7e057a40-bde4-4dd8-82d0-a0404f165911.png)

![cacule](https://user-images.githubusercontent.com/22229962/140631821-80137a63-3e92-4bdb-84e4-cc459b90109e.png)

**Comment by bigshans** [comment]
Thanks!
